/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:41a48c16-f7b8-44d9-bf93-e08668827ef3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_rCsOtCSR3",
    "aws_user_pools_web_client_id": "39a85seemlfgei49mcnoojgls3",
    "oauth": {}
};


export default awsmobile;
